/*
 *                            COPYRIGHT
 *
 *  lat2abc.c
 *  Copyright (C) 2018 Exstrom Laboratories LLC
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  A copy of the GNU General Public License is available on the internet at:
 *  http://www.gnu.org/copyleft/gpl.html
 *
 *  or you can write to:
 *
 *  The Free Software Foundation, Inc.
 *  675 Mass Ave
 *  Cambridge, MA 02139, USA
 *
 *  Exstrom Laboratories LLC contact:
 *  stefan(AT)exstrom.com
 *
 *  Exstrom Laboratories LLC
 *  Longmont, CO 80503, USA
 *
 */
// Compile: gcc -lm -o lat2abc lat2abc.c

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <ctype.h>

/***********************************************************************************/

int main(int argc, char *argv[])
{
  if( argc < 5 ){
    printf("\nUsage: %s inst key tempo file.lat\n", argv[0]);
    printf("  Converts walks on a square or triangular lattice to\n");
    printf("  melodies in abc notation. Walks can be generated by\n");
    printf("  program fsquare, fsquare2, fsquares or ftri. Input file\n");
    printf("  specifies: lattice size, note mapping, and any number\n");
    printf("  of lines containing starting point, walk, rhythm,\n");
    printf("  repeats, and rest. Result is printed to stdout.\n");
    printf("  inst  = MIDI instrument (program) number\n");
    printf("  key  = musical key, e.g. C\n");
    printf("  tempo  = beats per minute, e.g. 180\n");
    printf("  file.lat  = name of lattice file\n");
    return(-1);}

  FILE *fp = fopen(argv[4],"r");
  if(fp == NULL){
    printf("Error opening %s\n", argv[4]);
    return(1);}

  int i, j, k, nr, nc;
  fscanf(fp,"%d %d", &nc, &nr);
  char ***notes = (char ***)malloc(nr*sizeof(char **));
  char buff[512], pstr[64], rstr[64], rest[32]; // rest  = e.g. z4
  for(i = 0; i<nr; ++i){
    notes[i] = (char **)malloc(nc*sizeof(char *));
    for(j = 0; j<nc; ++j){
      fscanf(fp,"%s",buff);
      notes[i][j]=strdup(buff);}}

  fgetc(fp);
  int inst = atoi(argv[1]);
  char *key = strdup(argv[2]);
  int tempo = atoi(argv[3]);
  printf("X: 1\n");
  printf("T: lat2abc\n");
  printf("M: 4/4\n");
  printf("K: %s\n", key);
  printf("Q: %d\n", tempo);
  printf("%%%MIDI program %d\n", inst);

  int x, y, lp, lr, rep;
  while(fgets(buff,512,fp)){
    sscanf(buff,"%d %d %64s %64s %d %32s", &x, &y, pstr, rstr, &rep, rest);
    lp = strlen(pstr);  // length of path string
    lr = strlen(rstr);  // length of rhythm string
    printf("%s%c", notes[y][x], rstr[0]);
    for(j=0; j<rep; ++j){
      for(i=0; i<lp; ++i){
	switch(pstr[i]){
	case 'u': ++y; if(y>=nr) y=0; break;
	case 'd': --y; if(y<0) y=nr-1;break;
	case 'l': --x; if(x<0) x=nc-1;break;
	case 'r': ++x; if(x>=nc) x=0;break;
	case 'v': ++x; ++y; if(x>=nc) x=0; if(y>=nr) y=0; break;
	case 'e': --x; --y; if(x<0) x=nc-1; if(y<0) y=nr-1; break;
	case 's': break;} // s means do nothing
	printf("%s%c", notes[y][x], rstr[(i+1)%lr]);}}
    printf("%s\n", rest);}
  return(0);
}
